#!/usr/bin/env bash

# 1. Install HAProxy
apt-get update
apt-get install haproxy

# 2. Create HAProxy configuration file
cat > /etc/haproxy/haproxy.cfg << EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http-in
    bind *:80
    default_backend web-backend

backend web-backend
    balance roundrobin
    server 415741-web-01 54.208.64.8:80 check
    server 415741-web-02 34.232.70.70:80 check
EOF

# 3. Enable HAProxy init script
ln -s /usr/lib/haproxy/haproxy.init /etc/init.d/haproxy
update-rc.d haproxy defaults

# 4. Start HAProxy
sudo service haproxy restart
