#!/usr/bin/env bash
# bash script to make sure nginx gets port 80


rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
