#!/usr/bin/env bash
# This script is displaying "Best SChool" all but the 9th iteration

I=0
while ((I < 10)); do
    if ((I == 8)); then
        echo "Hi"
    else
        echo "Best School"
    fi
    I=$((I+1))
done
