#!/usr/bin/env bash
# Displays numbers from 1 to 20 and the following
# the string "bad luck from China" in the 4th loop
# the string "bad luck from Japan" in the 9th loop
# the string "bad luck from Italy" in the 17th loop

I=1

while [ $I -le 20 ]; do
    echo "$I"
    case "$I" in
	4)
	    echo "bad luck from China" ;;
	9)
	    echo "bad luck from Japan" ;;
	17)
	    echo "bad luck from Italy" ;;
    esac
    I=$((I+1))
done
