#!/usr/bin/env bash
# A simple Bash script to reload Gunicorn in a graceful way

# Get the PID of the Gunicorn master process
PID=$(ps aux | grep gunicorn | grep master | awk '{print $2}')

# Send the HUP signal to Gunicorn to reload gracefully
kill -HUP $PID

# Check the status of Gunicorn
gunicorn --check-config
